In [ ]:
import numpy as np
import pandas as pd
from sklearn.metrics import root_mean_squared_error  
from tabulate import tabulate

In [20]:
"""
1. Crea dos vectores con 10 valores aleatorios int entre 30 y 60 (vector 1) y con 10 valores float del 0.1 al 9.9 (vector 2) 
2. El primer vector se corresponderá con el valor real y el segundo vector con el predicho por el modelo
3. Calcula el RMSE con la función de scikit y con la fórmula tradicional.
4. Imprime el resultado
5. ¿Hay diferencia entre los resultados?
"""
v_real = np.random.randint(29,60,10)
v_predicho = np.random.random((10)) 
v_predicho *= 10

rmse_scikit = root_mean_squared_error(v_real,v_predicho)
print(f"RMSE con la función de scikit: {rmse_scikit:.2f}")

errores = (v_real - v_predicho) ** 2
mse = np.mean(errores)
rmse_formula = np.sqrt(mse)
print(f"RMSE con la fórmula tradicional: {rmse_formula:.2f}")

RMSE con la función de scikit: 39.55
RMSE con la fórmula tradicional: 39.55

In [32]:
# Leer el archivo CSV
df = pd.read_csv('Catalog_v2.csv')
df2 = pd.read_csv('Product_v6.csv')

# Mostrar las primeras 5 filas
#print("5 primeras filas:", df.head())
#print("5 primeras filas:", df2.head())
print("\nColumna Value:\n",df2['value'])

df2.columns = df2.columns.str.strip()
print("Columnas:", df2.columns)

print(tabulate(df2, headers='keys', tablefmt='psql'))
#Print de quinta columna segunda fila
print(df2.iloc[1,4])

"""
# Mostrar las últimas 5 filas con formato de tabla (tabulate)
print(tabulate(df, headers='keys', tablefmt='psql'))

#Eliminar espacios vacios y mostrar columnas
df.columns = df.columns.str.strip()
print("Todas las columnas:", df.columns)  

#Acceder a una columna por su nombre
print("Columna code:", df['code']) 

#Acceder a una columna por su index
print("Tercera columna:", df.iloc[:, 2])  # Accede a la tercera columna (índice 2)

#Acceder a una fila por su index
print("Tercera fila:", df.iloc[2, :])  # Accede a la tercera fila (índice 2)

# Ajustar pandas para mostrar todas las filas y columnas
pd.set_option('display.max_rows', None)  # Muestra todas las filas
pd.set_option('display.max_columns', None)  # Muestra todas las columnas

# Imprimir el DataFrame completo
print(df)"""

Columna Value:
 0     1250.0
1     1250.0
2     1250.0
3     1250.0
4     1250.0
       ...
81    1287.0
82    1456.0
83     833.0
84    1032.0
85     976.0
Name: value, Length: 86, dtype: float64
Columnas: Index(['partNumber', 'productType', 'category.code', 'brand.code',
       'family.code', 'line.code', 'productSegment.code', 'status', 'value',
       'valueCurrency', 'defaultQuantityUnits', 'name', 'description',
       'plannerCode', 'sourceLink'],
      dtype='object')
+----+--------------+---------------+-------------------------+---------------+------------------------------+---------------------+-----------------------+----------+---------+-----------------+------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+---------------+---------------------------------+
|    | partNumber   | productType   | category.code           | brand.code    | family.code                  | line.code           |   productSegment.code | status   |   value | valueCurrency   | defaultQuantityUnits   | name                                                                  | description                                                                                                | plannerCode   | sourceLink                      |
|----+--------------+---------------+-------------------------+---------------+------------------------------+---------------------+-----------------------+----------+---------+-----------------+------------------------+-----------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------+---------------+---------------------------------|
|  0 | PS-SL-A287   | PRODUCT       | Street Lighting         | Public Sector | Alliance                     | Rural               |                   nan | ACTIVE   |    1250 | USD             | EA                     | Alliance 150W HPS 25' Luminaire and Pole, Silver                      | Public Sector Street Lighting - Alliance 150W HPS 25' Luminaire and Pole, Silver                           | Lighting      | http://lighttree.com/PS-SL-A287 |
|  1 | PS-SL-A288   | PRODUCT       | Street Lighting         | Public Sector | Alliance                     | Rural               |                   nan | ACTIVE   |    1250 | USD             | EA                     | Alliance 100W HPS 25' Luminaire and Pole, Silver                      | Public Sector Street Lighting - Alliance 100W HPS 25' Luminaire and Pole, Silver                           | Lighting      | http://lighttree.com/PS-SL-A288 |
|  2 | PS-SL-H309   | PRODUCT       | Street Lighting         | Public Sector | Helm                         | Rural               |                   nan | ACTIVE   |    1250 | USD             | EA                     | Helm 150W HPS 30' Luminaire and Pole, Black                           | Public Sector Street Lighting - Helm 150W HPS 30' Luminaire and Pole, Black                                | Lighting      | http://lighttree.com/PS-SL-H309 |
|  3 | PS-SL-H310   | PRODUCT       | Street Lighting         | Public Sector | Helm                         | Rural               |                   nan | ACTIVE   |    1250 | USD             | EA                     | Helm 100W HPS 30' Luminaire and Pole, Black                           | Public Sector Street Lighting - Helm 100W HPS 30' Luminaire and Pole, Black                                | Lighting      | http://lighttree.com/PS-SL-H310 |
|  4 | PS-SL-F342   | PRODUCT       | Street Lighting         | Public Sector | Flatbush Avenue              | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Flatbush Avenue Twin 250W 30' Teardrop Lumi. and Pole, Black          | Public Sector Street Lighting - Flatbush Avenue Twin 250W 30' Teardrop Lumi. and Pole, Black               | Lighting      | http://lighttree.com/PS-SL-F342 |
|  5 | PS-SL-F343   | PRODUCT       | Street Lighting         | Public Sector | Flatbush Avenue              | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Flatbush Avenue Single 250W 30' Teardrop Lumi. and Pole, Black        | Public Sector Street Lighting - Flatbush Avenue Single 250W 30' Teardrop Lumi. and Pole, Black             | Lighting      | http://lighttree.com/PS-SL-F343 |
|  6 | PS-SL-F344   | PRODUCT       | Street Lighting         | Public Sector | Flatbush Avenue              | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Flatbush Avenue Twin 250W 30' Teardrop Lumi. and Pole, Brown          | Public Sector Street Lighting - Flatbush Avenue Twin 250W 30' Teardrop Lumi. and Pole, Brown               | Lighting      | http://lighttree.com/PS-SL-F344 |
|  7 | PS-SL-F345   | PRODUCT       | Street Lighting         | Public Sector | Flatbush Avenue              | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Flatbush Avenue Single 250W 30' Teardrop Lumi. and Pole, Brown        | Public Sector Street Lighting - Flatbush Avenue Single 250W 30' Teardrop Lumi. and Pole, Brown             | Lighting      | http://lighttree.com/PS-SL-F345 |
|  8 | PS-SL-B122   | PRODUCT       | Street Lighting         | Public Sector | Bishops Crook                | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Bishops Crook 250W HPS Historical teardrop Lumi. and pole             | Public Sector Street Lighting - Bishops Crook 250W HPS Historical teardrop Lumi. and pole                  | Lighting      | http://lighttree.com/PS-SL-B122 |
|  9 | PS-SL-A123   | PRODUCT       | Street Lighting         | Public Sector | Bishops Crook                | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Bishops Crook IES Type III Historical teardrop Lumi. and pole         | Public Sector Street Lighting - Bishops Crook IES Type III Historical teardrop Lumi. and pole              | Lighting      | http://lighttree.com/PS-SL-A123 |
| 10 | PS-SL-C280   | PRODUCT       | Street Lighting         | Public Sector | City Light                   | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | City Light 150W HPS 30' Luminaire and Pole, Black                     | Public Sector Street Lighting - City Light 150W HPS 30' Luminaire and Pole, Black                          | Lighting      | http://lighttree.com/PS-SL-C280 |
| 11 | PS-SL-C193   | PRODUCT       | Street Lighting         | Public Sector | City Light                   | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | City Light 100W HPS 30' Luminaire and Pole, Black                     | Public Sector Street Lighting - City Light 100W HPS 30' Luminaire and Pole, Black                          | Lighting      | http://lighttree.com/PS-SL-C193 |
| 12 | PS-SL-L327   | PRODUCT       | Street Lighting         | Public Sector | LED Type E                   | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | LED Type E Twin 250W 30' Teardrop Lumi. and Pole, Brown               | Public Sector Street Lighting - LED Type E Twin 250W 30' Teardrop Lumi. and Pole, Brown                    | Lighting      | http://lighttree.com/PS-SL-L327 |
| 13 | PS-SL-L393   | PRODUCT       | Street Lighting         | Public Sector | LED Type E                   | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | LED Type E Single 250W 30' Teardrop Lumi. and Pole, Brown             | Public Sector Street Lighting - LED Type E Single 250W 30' Teardrop Lumi. and Pole, Brown                  | Lighting      | http://lighttree.com/PS-SL-L393 |
| 14 | PS-SL-KIT    | PRODUCT       | Street Lighting         | Public Sector | All                          | City                |                   nan | ACTIVE   |       0 | USD             | EA                     | Public Sector Street Lighting Universal Installation Kit              | Public Sector Street Lighting - Public Sector Street Lighting Universal Installation Kit                   | Lighting      | http://lighttree.com/PS-SL-KIT  |
| 15 | PS-SL-INFO   | PRODUCT       | Street Lighting         | Public Sector | All                          | City                |                   nan | INACTIVE |       0 | USD             | EA                     | Public Sector Street Lighting Universal Installation Instructions     | Public Sector Street Lighting - Public Sector Street Lighting Universal Installation Instructions          | Lighting      | http://lighttree.com/PS-SL-INFO |
| 16 | PS-PL-C295   | PRODUCT       | Pedestrian Lighting     | Public Sector | Cobra Head                   | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Cobra Head 150W HPS 30' Luminaire and Pole, Black                     | Public Sector Pedestrian Lighting - Cobra Head 150W HPS 30' Luminaire and Pole, Black                      | Lighting      | http://lighttree.com/PS-PL-C295 |
| 17 | PS-PL-C167   | PRODUCT       | Pedestrian Lighting     | Public Sector | Cobra Head                   | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Cobra Head 100W HPS 30' Luminaire and Pole, Black                     | Public Sector Pedestrian Lighting - Cobra Head 100W HPS 30' Luminaire and Pole, Black                      | Lighting      | http://lighttree.com/PS-PL-C167 |
| 18 | PS-PL-S459   | PRODUCT       | Pedestrian Lighting     | Public Sector | Stad                         | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Stad Twin 250W 30' Teardrop Lumi. and Pole, Black                     | Public Sector Pedestrian Lighting - Stad Twin 250W 30' Teardrop Lumi. and Pole, Black                      | Lighting      | http://lighttree.com/PS-PL-S459 |
| 19 | PS-PL-S236   | PRODUCT       | Pedestrian Lighting     | Public Sector | Stad                         | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Stad Single 250W 30' Teardrop Lumi. and Pole, Black                   | Public Sector Pedestrian Lighting - Stad Single 250W 30' Teardrop Lumi. and Pole, Black                    | Lighting      | http://lighttree.com/PS-PL-S236 |
| 20 | PS-PL-F206   | PRODUCT       | Pedestrian Lighting     | Public Sector | Fulton                       | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Fulton Twin 250W 30' Teardrop Lumi. and Pole, Black                   | Public Sector Pedestrian Lighting - Fulton Twin 250W 30' Teardrop Lumi. and Pole, Black                    | Lighting      | http://lighttree.com/PS-PL-F206 |
| 21 | PS-PL-F158   | PRODUCT       | Pedestrian Lighting     | Public Sector | Fulton                       | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Fulton Single 250W 30' Teardrop Lumi. and Pole, Black                 | Public Sector Pedestrian Lighting - Fulton Single 250W 30' Teardrop Lumi. and Pole, Black                  | Lighting      | http://lighttree.com/PS-PL-F158 |
| 22 | PS-PL-F242   | PRODUCT       | Pedestrian Lighting     | Public Sector | Flushing Meadows             | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Flushing Meadows 150W HPS 25' Luminaire and Pole, Silver              | Public Sector Pedestrian Lighting - Flushing Meadows 150W HPS 25' Luminaire and Pole, Silver               | Lighting      | http://lighttree.com/PS-PL-F242 |
| 23 | PS-PL-F388   | PRODUCT       | Pedestrian Lighting     | Public Sector | Flushing Meadows             | City                |                   nan | ACTIVE   |    1250 | USD             | EA                     | Flushing Meadows 100W HPS 25' Luminaire and Pole, Silver              | Public Sector Pedestrian Lighting - Flushing Meadows 100W HPS 25' Luminaire and Pole, Silver               | Lighting      | http://lighttree.com/PS-PL-F388 |
| 24 | PS-PL-W140   | PRODUCT       | Pedestrian Lighting     | Public Sector | World's Fair                 | Special application |                   nan | ACTIVE   |    1250 | USD             | EA                     | World's Fair 150W HPS 30' Luminaire and Pole, Black                   | Public Sector Pedestrian Lighting - World's Fair 150W HPS 30' Luminaire and Pole, Black                    | Lighting      | http://lighttree.com/PS-PL-W140 |
| 25 | PS-PL-W381   | PRODUCT       | Pedestrian Lighting     | Public Sector | World's Fair                 | Special application |                   nan | ACTIVE   |    1250 | USD             | EA                     | World's Fair 100W HPS 30' Luminaire and Pole, Black                   | Public Sector Pedestrian Lighting - World's Fair 100W HPS 30' Luminaire and Pole, Black                    | Lighting      | http://lighttree.com/PS-PL-W381 |
| 26 | PS-PL-R186   | PRODUCT       | Pedestrian Lighting     | Public Sector | Round Top Head               | Special application |                   nan | ACTIVE   |    1250 | USD             | EA                     | Round Top Head IES Type III Historical teardrop Lumi. and pole        | Public Sector Pedestrian Lighting - Round Top Head IES Type III Historical teardrop Lumi. and pole         | Lighting      | http://lighttree.com/PS-PL-R186 |
| 27 | PS-PL-KIT    | PRODUCT       | Pedestrian Lighting     | Public Sector | All                          | Special application |                   nan | ACTIVE   |       0 | USD             | EA                     | Public Sector Pedestrian Lighting Universal Installation Kit          | Public Sector Pedestrian Lighting - Public Sector Pedestrian Lighting Universal Installation Kit           | Lighting      | http://lighttree.com/PS-PL-KIT  |
| 28 | PS-PL-INFO   | PRODUCT       | Pedestrian Lighting     | Public Sector | All                          | Special application |                   nan | ACTIVE   |       0 | USD             | EA                     | Public Sector Pedestrian Lighting Universal Installation Instructions | Public Sector Pedestrian Lighting - Public Sector Pedestrian Lighting Universal Installation Instructions  | Lighting      | http://lighttree.com/PS-PL-INFO |
| 29 | PS-TS-T264   | PRODUCT       | Traffic Signal Poles    | Public Sector | Type M-2 Traffic Signal Pole | Traffic             |                   nan | ACTIVE   |    1450 | USD             | EA                     | Type M-2 Traffic Signal Pole                                          | Public Sector Traffic Signal Poles - Type M-2 Traffic Signal Pole                                          | Poles         | http://lighttree.com/PS-TS-T264 |
| 30 | PS-TS-A318   | PRODUCT       | Traffic Signal Poles    | Public Sector | Alliance Traffic Signal Pole | Traffic             |                   nan | ACTIVE   |    1450 | USD             | EA                     | Alliance Traffic Signal Pole                                          | Public Sector Traffic Signal Poles - Alliance Traffic Signal Pole                                          | Poles         | http://lighttree.com/PS-TS-A318 |
| 31 | PS-TS-KIT    | PRODUCT       | Traffic Signal Poles    | Public Sector | All                          | Traffic             |                   nan | ACTIVE   |       0 | USD             | EA                     | Public Sector Traffic Signal Pole Universal Installation Kit          | Public Sector Traffic Signal Poles - Public Sector Traffic Signal Pole Universal Installation Kit          | Poles         | http://lighttree.com/PS-TS-KIT  |
| 32 | PS-TS-INFO   | PRODUCT       | Traffic Signal Poles    | Public Sector | All                          | Traffic             |                   nan | INACTIVE |       0 | USD             | EA                     | Public Sector Traffic Signal Pole Universal Installation Instructions | Public Sector Traffic Signal Poles - Public Sector Traffic Signal Pole Universal Installation Instructions | Poles         | http://lighttree.com/PS-TS-INFO |
| 33 | CO-CO-V310   | PRODUCT       | Controls                | Commercial    | Ventura                      | nan                 |                   nan | ACTIVE   |     100 | USD             | EA                     | Ventura 48VDC control module                                          | Commercial Controls - Ventura 48VDC control module                                                         | Electrical    | http://lighttree.com/CO-CO-V310 |
| 34 | CO-CO-N311   | PRODUCT       | Controls                | Commercial    | Northridge                   | nan                 |                   nan | ACTIVE   |     250 | USD             | EA                     | Northridge  230VAC control module                                     | Commercial Controls - Northridge  230VAC control module                                                    | Electrical    | http://lighttree.com/CO-CO-N311 |
| 35 | CO-CO-M328   | PRODUCT       | Controls                | Commercial    | Miramar                      | nan                 |                   nan | ACTIVE   |     125 | USD             | EA                     | Miramar  110VAC control module                                        | Commercial Controls - Miramar  110VAC control module                                                       | Electrical    | http://lighttree.com/CO-CO-M328 |
| 36 | CO-DL-T316   | PRODUCT       | Downlights              | Commercial    | Tulare                       | nan                 |                   nan | ACTIVE   |      55 | USD             | EA                     | Tulare 6 inch recessed downlight                                      | Commercial Downlights - Tulare 6 inch recessed downlight                                                   | Lighting      | http://lighttree.com/CO-DL-T316 |
| 37 | CO-DL-A239   | PRODUCT       | Downlights              | Commercial    | Alameda                      | nan                 |                   nan | ACTIVE   |      48 | USD             | EA                     | Alameda 5 inch recessed downlight                                     | Commercial Downlights - Alameda 5 inch recessed downlight                                                  | Lighting      | http://lighttree.com/CO-DL-A239 |
| 38 | CO-DL-A230   | PRODUCT       | Downlights              | Commercial    | Alpine                       | nan                 |                   nan | ACTIVE   |      51 | USD             | EA                     | Alpine Water resistant 6 inch downlight                               | Commercial Downlights - Alpine Water resistant 6 inch downlight                                            | Lighting      | http://lighttree.com/CO-DL-A230 |
| 39 | CO-RD-I380   | PRODUCT       | Retrofit Downlights     | Commercial    | Imperial                     | nan                 |                   nan | ACTIVE   |      78 | USD             | EA                     | Imperial  6 inch recessed downlight                                   | Commercial Retrofit Downlights - Imperial  6 inch recessed downlight                                       | Lighting      | http://lighttree.com/CO-RD-I380 |

'\n# Mostrar las últimas 5 filas con formato de tabla (tabulate)\nprint(tabulate(df, headers=\'keys\', tablefmt=\'psql\'))\n\n#Eliminar espacios vacios y mostrar columnas\ndf.columns = df.columns.str.strip()\nprint("Todas las columnas:", df.columns)  \n\n#Acceder a una columna por su nombre\nprint("Columna code:", df[\'code\']) \n\n#Acceder a una columna por su index\nprint("Tercera columna:", df.iloc[:, 2])  # Accede a la tercera columna (índice 2)\n\n#Acceder a una fila por su index\nprint("Tercera fila:", df.iloc[2, :])  # Accede a la tercera fila (índice 2)\n\n# Ajustar pandas para mostrar todas las filas y columnas\npd.set_option(\'display.max_rows\', None)  # Muestra todas las filas\npd.set_option(\'display.max_columns\', None)  # Muestra todas las columnas\n\n# Imprimir el DataFrame completo\nprint(df)'

In [1]:
#Acceder a la columna value
import pandas as pd
import numpy as np
from tabulate import tabulate
df2 = pd.read_csv('Product_v6.csv')
print(tabulate(df2, headers='keys', tablefmt='psql'))

array_np = np.array(df2['value'])
resultado_np = np.sqrt(array_np)
df2["raiz_cuadrada"] = resultado_np
df2.to_csv("datos_modificados.csv", index = False)

#Filtrar filas donde la columna 'Value' tenga valores mayores que 1000
df2.loc[df2['value'] > 1000, 'value'] *=2 #df.loc[condición, "nombre_columna"]


#APLICA UN 10% A TODOS LOS VALORES DE LA COLUMNA RAÍZ CUADRADA Y GUARDA ESOS VALORES EN UNA NUEVA COLUMNA QUE SE VA A LLAMAR R.C BRUTA
#COGE TODOS LOS VALORES DE LA COLUMNA R.C BUTA QUE SEAN MENORES DE 60 Y MAYORES DE 40 Y LES VAMOS A ELEVAR AL CUADRADO
array = np.array(df2['raiz_cuadrada']) 
porcentaje = array * 0.10
resultado = array - porcentaje
df2['rc_bruta'] = resultado
df2.to_csv("porcentaje.csv", index = False)

#df2.loc[df2['rc_bruta'] < 60 and df2['rc_bruta'] > 40, 'rc_bruta'] **2
df2.to_csv("resultado.csv", index = False)
print(df2.head())

ModuleNotFoundError: No module named 'tabulate'

1- Leer el csv y convertiro en DataFrame <br>
2- Almacenar en un array los valores de la columna "order.orderIdentifier", y en otro array los valores de la columna "value" <br>
3- Aplizar la normalización Z-Score a los ambas columnas.<br>
4- Vamos a comprobar si realmente la desviación de los valores normalizados es 1<br>
y si la media de los valores normalizados es 0 (o ronda el 0)<br>
EL CSV se llama ShipmentLine_v3

In [16]:
df_shipment = pd.read_csv("ShipmentLine_v3.csv")
orderId = np.array(df_shipment["order.orderIdentifier"])
value = np.array(df_shipment["value"])

df_shipment['orderIdNormalizado'] = (orderId - orderId.mean()) / orderId.std()
df_shipment['valueNormalizado'] = (value - value.mean()) / value.std()
df_shipment['desviacion_orderNormalizado'] = df_shipment['orderIdNormalizado'].std()
df_shipment['desviacion_valueNormalizado'] = df_shipment['valueNormalizado'].std()

df_shipment

,shipment.shipmentIdentifier,shipmentLineNumber,shipment.shipmentType,order.orderIdentifier,orderLine.orderLineNumber,dateCreated,quantity,quantityUnits,value,valueCurrency,orderIdNormalizado,valueNormalizado,desviacion_orderNormalizado,desviacion_valueNormalizado
0,3004539,100,OUTBOUND,100044355,100,2021-07-05T00:00:00,400,EA,500000,USD,-2.134375,1.767151,1.002509,1.002509
1,3004539,200,OUTBOUND,100044355,200,2021-07-05T00:00:00,400,EA,0,USD,-2.134375,-0.407217,1.002509,1.002509
2,3004539,300,OUTBOUND,100044355,300,2021-07-05T00:00:00,400,EA,0,USD,-2.134375,-0.407217,1.002509,1.002509
3,3004540,100,OUTBOUND,100044354,100,2021-07-05T00:00:00,208,EA,260000,USD,-2.134375,0.723454,1.002509,1.002509
4,3004540,200,OUTBOUND,100044354,200,2021-07-05T00:00:00,208,EA,0,USD,-2.134375,-0.407217,1.002509,1.002509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,FJMDL6,100,INBOUND,1000567482,100,2021-07-08T00:00:00,56,EA,1344,USD,0.468522,-0.401372,1.002509,1.002509
196,YUJOYM,100,INBOUND,1000567486,100,2021-07-15T00:00:00,44,EA,56760,USD,0.468522,-0.160383,1.002509,1.002509
197,Y15P9J,100,INBOUND,1000567494,100,2021-06-16T00:00:00,124,EA,43400,USD,0.468522,-0.218482,1.002509,1.002509
198,TRYYNK,100,INBOUND,1000567497,100,2021-07-15T00:00:00,44,EA,132,USD,0.468522,-0.406643,1.002509,1.002509
199,ANQWZY,100,INBOUND,1000567500,100,2021-07-08T00:00:00,56,EA,66080,USD,0.468522,-0.119852,1.002509,1.002509

## Pruebas y apuntes del 17 de febrero - pandas y lectura , manipulación de csvs

In [2]:

# DataFrames de ejemplo
df1 = pd.DataFrame({
    'ID': [1, 2, 3, 4],
    'Nombre': ['Ana', 'Luis', 'Pedro', 'Marta']
})

df2 = pd.DataFrame({
    'ID': [3, 4, 5],
    'Salario': [25000, 45000, 35000]
})

# Fusión de ambos DataFrames por la columna 'ID' (común)
df_merged = pd.merge(df1, df2, how='inner', on='ID')
print(df_merged)

# Fusión externa para mantener todos los datos
df_merged_outer = pd.merge(df1, df2, how='outer', on='ID')
print(df_merged_outer)

# Fusión utilizando diferentes nombres de columnas
df1 = pd.DataFrame({
    'ID_cliente': [1, 2, 3, 4],
    'Nombre': ['Ana', 'Luis', 'Pedro', 'Marta']
})

df2 = pd.DataFrame({
    'ID_usuario': [3, 4, 5],
    'Salario': [25000, 45000, 35000]
})

# Fusión utilizando las columnas 'ID_cliente' de df1 y 'ID_usuario' de df2
df_merged_diff_columns = pd.merge(df1, df2, how='inner', left_on='ID_cliente', right_on='ID_usuario')
print(df_merged_diff_columns)

   ID Nombre  Salario
0   3  Pedro    25000
1   4  Marta    45000
   ID Nombre  Salario
0   1    Ana      NaN
1   2   Luis      NaN
2   3  Pedro  25000.0
3   4  Marta  45000.0
4   5    NaN  35000.0
   ID_cliente Nombre  ID_usuario  Salario
0           3  Pedro           3    25000
1           4  Marta           4    45000

In [3]:
from sklearn.datasets import load_breast_cancer

# Cargar el dataset
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)

# Añadir la columna 'target' (maligno o benigno)
df['target'] = data.target

# Mostrar las primeras filas para ver cómo está estructurado el DataFrame
print(df.head())

   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840
1        20.57         17.77          132.90     1326.0          0.08474
2        19.69         21.25          130.00     1203.0          0.10960
3        11.42         20.38           77.58      386.1          0.14250
4        20.29         14.34          135.10     1297.0          0.10030

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419
1           0.07864          0.0869              0.07017         0.1812
2           0.15990          0.1974              0.12790         0.2069
3           0.28390          0.2414              0.10520         0.2597
4           0.13280          0.1980              0.10430         0.1809

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0
1                 0.05667  ...          23.41           158.80      1956.0
2                 0.05999  ...          25.53           152.50      1709.0
3                 0.09744  ...          26.50            98.87       567.7
4                 0.05883  ...          16.67           152.20      1575.0

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654
1            0.1238             0.1866           0.2416                0.1860
2            0.1444             0.4245           0.4504                0.2430
3            0.2098             0.8663           0.6869                0.2575
4            0.1374             0.2050           0.4000                0.1625

   worst symmetry  worst fractal dimension  target
0          0.4601                  0.11890       0
1          0.2750                  0.08902       0
2          0.3613                  0.08758       0
3          0.6638                  0.17300       0
4          0.2364                  0.07678       0

[5 rows x 31 columns]

In [13]:
# Crear un DataFrame de ejemplo
data = {
    'Departamento': ['Ventas', 'Ventas', 'IT', 'IT', 'RRHH', 'RRHH', 'Ventas'],
    'Empleado': ['Ana', 'Luis', 'Pedro', 'Marta', 'Sofía', 'Carlos', 'David'],
    'Salario': [30000, 50000, 60000, 55000, 40000, 42000, 48000],
    'Edad': [25, 30, 40, 35, 28, 45, 32],
    'sexo': ["Hombre","Mujer","Hombre","Mujer","Hombre","Hombre","Mujer"]
}

df = pd.DataFrame(data)

# Agrupar por varias columnas (Departamento y Edad agrupada en rangos)
df['Grupo_Edad'] = pd.cut(df['Edad'], bins=[20, 30, 40, 50], labels=['20-30', '30-40', '40-50'])
grupo_edad_salario = df.groupby(['Departamento', 'Grupo_Edad'])['Salario'].mean()
print("Salario promedio por departamento y grupo de edad:\n", grupo_edad_salario, "\n")

"""Crea una columna que especifique el sexo de los empleados. A continuación, agrupa los datos por Departamentos y además por sexo, especifica etiquetas "Hombre y "Mujer para cada grupo """

grupo_departamento_sexo = df.groupby(['Departamento', 'sexo']).count()
print("depasexo", grupo_departamento_sexo)

Salario promedio por departamento y grupo de edad:
 Departamento  Grupo_Edad
IT            20-30             NaN
              30-40         57500.0
              40-50             NaN
RRHH          20-30         40000.0
              30-40             NaN
              40-50         42000.0
Ventas        20-30         40000.0
              30-40         48000.0
              40-50             NaN
Name: Salario, dtype: float64

depasexo                      Empleado  Salario  Edad  Grupo_Edad
Departamento sexo
IT           Hombre         1        1     1           1
             Mujer          1        1     1           1
RRHH         Hombre         2        2     2           2
Ventas       Hombre         1        1     1           1
             Mujer          2        2     2           2

C:\Users\Aaron\AppData\Local\Temp\ipykernel_11764\1584843606.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grupo_edad_salario = df.groupby(['Departamento', 'Grupo_Edad'])['Salario'].mean()